package lwjglalti.input;

import org.lwjgl.input.Keyboard;

import static org.lwjgl.glfw.GLFW.GLFW_KEY_0;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_1;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_2;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_3;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_4;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_5;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_6;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_7;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_8;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_9;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_A;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_APOSTROPHE;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_B;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_BACKSLASH;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_BACKSPACE;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_C;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_CAPS_LOCK;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_COMMA;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_D;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_DELETE;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_DOWN;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_E;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_END;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_ENTER;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_EQUAL;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_ESCAPE;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F1;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F10;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F11;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F12;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F13;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F14;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F15;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F16;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F17;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F18;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F19;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F2;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F3;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F4;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F5;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F6;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F7;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F8;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F9;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_G;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_GRAVE_ACCENT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_H;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_HOME;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_I;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_INSERT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_J;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_K;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_0;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_1;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_2;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_3;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_4;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_5;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_6;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_7;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_8;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_9;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_ADD;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_DECIMAL;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_DIVIDE;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_ENTER;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_EQUAL;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_MULTIPLY;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_SUBTRACT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_L;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_ALT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_BRACKET;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_CONTROL;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_SHIFT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_SUPER;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_M;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_MENU;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_MINUS;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_N;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_NUM_LOCK;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_O;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_P;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_PAGE_DOWN;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_PAGE_UP;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_PAUSE;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_PERIOD;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_Q;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_R;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_ALT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_BRACKET;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_CONTROL;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_SHIFT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_SUPER;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_S;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_SCROLL_LOCK;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_SEMICOLON;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_SLASH;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_SPACE;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_T;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_TAB;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_U;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_UP;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_V;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_W;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_X;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_Y;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_Z;

public class GlfwToLwjgl2Key {

    private GlfwToLwjgl2Key() {
        // static api
    }

    public static int adapt(int glfwKey) {
        return switch (glfwKey) {
            case GLFW_KEY_ESCAPE -> Keyboard.KEY_ESCAPE;
            case GLFW_KEY_1 -> Keyboard.KEY_1;
            case GLFW_KEY_2 -> Keyboard.KEY_2;
            case GLFW_KEY_3 -> Keyboard.KEY_3;
            case GLFW_KEY_4 -> Keyboard.KEY_4;
            case GLFW_KEY_5 -> Keyboard.KEY_5;
            case GLFW_KEY_6 -> Keyboard.KEY_6;
            case GLFW_KEY_7 -> Keyboard.KEY_7;
            case GLFW_KEY_8 -> Keyboard.KEY_8;
            case GLFW_KEY_9 -> Keyboard.KEY_9;
            case GLFW_KEY_0 -> Keyboard.KEY_0;
            case GLFW_KEY_MINUS -> Keyboard.KEY_MINUS;
            case GLFW_KEY_EQUAL -> Keyboard.KEY_EQUALS;
            case GLFW_KEY_BACKSPACE -> Keyboard.KEY_BACK;
            case GLFW_KEY_TAB -> Keyboard.KEY_TAB;
            case GLFW_KEY_Q -> Keyboard.KEY_Q;
            case GLFW_KEY_W -> Keyboard.KEY_W;
            case GLFW_KEY_E -> Keyboard.KEY_E;
            case GLFW_KEY_R -> Keyboard.KEY_R;
            case GLFW_KEY_T -> Keyboard.KEY_T;
            case GLFW_KEY_Y -> Keyboard.KEY_Y;
            case GLFW_KEY_U -> Keyboard.KEY_U;
            case GLFW_KEY_I -> Keyboard.KEY_I;
            case GLFW_KEY_O -> Keyboard.KEY_O;
            case GLFW_KEY_P -> Keyboard.KEY_P;
            case GLFW_KEY_LEFT_BRACKET -> Keyboard.KEY_LBRACKET;
            case GLFW_KEY_RIGHT_BRACKET -> Keyboard.KEY_RBRACKET;
            case GLFW_KEY_ENTER -> Keyboard.KEY_RETURN;
            case GLFW_KEY_LEFT_CONTROL -> Keyboard.KEY_LCONTROL;
            case GLFW_KEY_A -> Keyboard.KEY_A;
            case GLFW_KEY_S -> Keyboard.KEY_S;
            case GLFW_KEY_D -> Keyboard.KEY_D;
            case GLFW_KEY_F -> Keyboard.KEY_F;
            case GLFW_KEY_G -> Keyboard.KEY_G;
            case GLFW_KEY_H -> Keyboard.KEY_H;
            case GLFW_KEY_J -> Keyboard.KEY_J;
            case GLFW_KEY_K -> Keyboard.KEY_K;
            case GLFW_KEY_L -> Keyboard.KEY_L;
            case GLFW_KEY_SEMICOLON -> Keyboard.KEY_SEMICOLON;
            case GLFW_KEY_APOSTROPHE -> Keyboard.KEY_APOSTROPHE;
            case GLFW_KEY_GRAVE_ACCENT -> Keyboard.KEY_GRAVE;
            case GLFW_KEY_LEFT_SHIFT -> Keyboard.KEY_LSHIFT;
            case GLFW_KEY_BACKSLASH -> Keyboard.KEY_BACKSLASH;
            case GLFW_KEY_Z -> Keyboard.KEY_Z;
            case GLFW_KEY_X -> Keyboard.KEY_X;
            case GLFW_KEY_C -> Keyboard.KEY_C;
            case GLFW_KEY_V -> Keyboard.KEY_V;
            case GLFW_KEY_B -> Keyboard.KEY_B;
            case GLFW_KEY_N -> Keyboard.KEY_N;
            case GLFW_KEY_M -> Keyboard.KEY_M;
            case GLFW_KEY_COMMA -> Keyboard.KEY_COMMA;
            case GLFW_KEY_PERIOD -> Keyboard.KEY_PERIOD;
            case GLFW_KEY_SLASH -> Keyboard.KEY_SLASH;
            case GLFW_KEY_RIGHT_SHIFT -> Keyboard.KEY_RSHIFT;
            case GLFW_KEY_KP_MULTIPLY -> Keyboard.KEY_MULTIPLY;
            case GLFW_KEY_LEFT_ALT -> Keyboard.KEY_LMENU;
            case GLFW_KEY_SPACE -> Keyboard.KEY_SPACE;
            case GLFW_KEY_CAPS_LOCK -> Keyboard.KEY_CAPITAL;
            case GLFW_KEY_F1 -> Keyboard.KEY_F1;
            case GLFW_KEY_F2 -> Keyboard.KEY_F2;
            case GLFW_KEY_F3 -> Keyboard.KEY_F3;
            case GLFW_KEY_F4 -> Keyboard.KEY_F4;
            case GLFW_KEY_F5 -> Keyboard.KEY_F5;
            case GLFW_KEY_F6 -> Keyboard.KEY_F6;
            case GLFW_KEY_F7 -> Keyboard.KEY_F7;
            case GLFW_KEY_F8 -> Keyboard.KEY_F8;
            case GLFW_KEY_F9 -> Keyboard.KEY_F9;
            case GLFW_KEY_F10 -> Keyboard.KEY_F10;
            case GLFW_KEY_NUM_LOCK -> Keyboard.KEY_NUMLOCK;
            case GLFW_KEY_SCROLL_LOCK -> Keyboard.KEY_SCROLL;
            case GLFW_KEY_KP_7 -> Keyboard.KEY_NUMPAD7;
            case GLFW_KEY_KP_8 -> Keyboard.KEY_NUMPAD8;
            case GLFW_KEY_KP_9 -> Keyboard.KEY_NUMPAD9;
            case GLFW_KEY_KP_SUBTRACT -> Keyboard.KEY_SUBTRACT;
            case GLFW_KEY_KP_4 -> Keyboard.KEY_NUMPAD4;
            case GLFW_KEY_KP_5 -> Keyboard.KEY_NUMPAD5;
            case GLFW_KEY_KP_6 -> Keyboard.KEY_NUMPAD6;
            case GLFW_KEY_KP_ADD -> Keyboard.KEY_ADD;
            case GLFW_KEY_KP_1 -> Keyboard.KEY_NUMPAD1;
            case GLFW_KEY_KP_2 -> Keyboard.KEY_NUMPAD2;
            case GLFW_KEY_KP_3 -> Keyboard.KEY_NUMPAD3;
            case GLFW_KEY_KP_0 -> Keyboard.KEY_NUMPAD0;
            case GLFW_KEY_KP_DECIMAL -> Keyboard.KEY_DECIMAL;
            case GLFW_KEY_F11 -> Keyboard.KEY_F11;
            case GLFW_KEY_F12 -> Keyboard.KEY_F12;
            case GLFW_KEY_F13 -> Keyboard.KEY_F13;
            case GLFW_KEY_F14 -> Keyboard.KEY_F14;
            case GLFW_KEY_F15 -> Keyboard.KEY_F15;
            case GLFW_KEY_F16 -> Keyboard.KEY_F16;
            case GLFW_KEY_F17 -> Keyboard.KEY_F17;
            case GLFW_KEY_F18 -> Keyboard.KEY_F18;
            case GLFW_KEY_F19 -> Keyboard.KEY_F19;
            case GLFW_KEY_KP_EQUAL -> Keyboard.KEY_NUMPADEQUALS;
            case GLFW_KEY_RIGHT_CONTROL -> Keyboard.KEY_RCONTROL;
            case GLFW_KEY_KP_DIVIDE -> Keyboard.KEY_DIVIDE;
            case GLFW_KEY_RIGHT_ALT -> Keyboard.KEY_RMENU;
            case GLFW_KEY_PAUSE -> Keyboard.KEY_PAUSE;
            case GLFW_KEY_HOME -> Keyboard.KEY_HOME;
            case GLFW_KEY_UP -> Keyboard.KEY_UP;
            case GLFW_KEY_PAGE_UP -> Keyboard.KEY_PRIOR;
            case GLFW_KEY_LEFT -> Keyboard.KEY_LEFT;
            case GLFW_KEY_RIGHT -> Keyboard.KEY_RIGHT;
            case GLFW_KEY_END -> Keyboard.KEY_END;
            case GLFW_KEY_DOWN -> Keyboard.KEY_DOWN;
            case GLFW_KEY_PAGE_DOWN -> Keyboard.KEY_NEXT;
            case GLFW_KEY_INSERT -> Keyboard.KEY_INSERT;
            case GLFW_KEY_DELETE -> Keyboard.KEY_DELETE;
            case GLFW_KEY_KP_ENTER -> Keyboard.KEY_NUMPADENTER;
            case GLFW_KEY_LEFT_SUPER -> Keyboard.KEY_LMETA;
            case GLFW_KEY_RIGHT_SUPER -> Keyboard.KEY_RMETA;
            case GLFW_KEY_MENU -> Keyboard.KEY_APPS;

// UNMAPPED KEYS, and i am pretty sure they are unmappable
//            case _ -> Keyboard.KEY_KANA;
//            case _ -> Keyboard.KEY_CONVERT;
//            case _ -> Keyboard.KEY_NOCONVERT;
//            case _ -> Keyboard.KEY_YEN;
//            case _ -> Keyboard.KEY_CIRCUMFLEX;
//            case _ -> Keyboard.KEY_AT;
//            case _ -> Keyboard.KEY_COLON;
//            case _ -> Keyboard.KEY_UNDERLINE;
//            case _ -> Keyboard.KEY_KANJI;
//            case _ -> Keyboard.KEY_STOP;
//            case _ -> Keyboard.KEY_AX;
//            case _ -> Keyboard.KEY_UNLABELED;
//            case _ -> Keyboard.KEY_SECTION;
//            case _ -> Keyboard.KEY_NUMPADCOMMA;
//            case _ -> Keyboard.KEY_SYSRQ;
//            case _ -> Keyboard.KEY_FUNCTION;
//            case _ -> Keyboard.KEY_CLEAR;
//            case _ -> Keyboard.KEY_POWER;
//            case _ -> Keyboard.KEY_SLEEP;

            default -> Keyboard.KEY_NONE;
        };
    }
}
